name: CI GJR - Test

on:
  push:
    branches: [main, Verona, CADU, DANIEL]
  pull_request:
    branches: [main, Verona, CADU, DANIEL]

  workflow_dispatch:

jobs:
  API-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jurplel/install-qt-action@v2

      - name: Build API
        run: |
          cd '${{ github.workspace }}/bin/API'
          qmake ../../API/API.pro
          make

      - name: Build Functional Tests
        run: |
          cd '${{ github.workspace }}/bin/FUNCTIONAL'
          qmake ../../FUNCTIONAL/FUNCTIONAL.pro
          make

      - name: Build Unit Tests
        run: |
          cd '${{ github.workspace }}/bin/UNIT'
          qmake ../../UNIT/UNIT.pro
          make

      - name: Run Functional Tests
        run: |
          cd '${{ github.workspace }}/bin/FUNCTIONAL'
          chmod +x ./ci_execution.sh
          ./ci_execution.sh "./FUNCTIONAL"

      - name: Run Unit Tests
        run: |
          cd '${{ github.workspace }}/bin/UNIT'
          chmod +x ./ci_execution.sh
          ./ci_execution.sh "./UNIT"
