name: CI GJR

on:
  push:
    branches: [main, tests, display]
  pull_request:
    branches: [main, tests, display]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run unit and functional tests
        run: |
          cd Runtime
          make clean
          make api
          make test_func
          make test_unit
          cd ./bin
          chmod +x funcional_tests
          chmod +x unit_tests
          cd ../
          make run_unit
          make run_func
