name: CI GJR

on:
  push:
    branches: [main, tests, display]
  pull_request:
    branches: [main, tests, display]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: jurplel/install-qt-action@v2
#      - uses: actions/checkout@v2

      - name: Run unit and functional tests
        run: |
          echo $PWD
          cd ./bin/API/
          qmake ../../API/API.pro
          make
          cd ../FUNCTIONAL/
          qmake ../../FUNCTIONAL/FUNCTIONAL.pro
          make
          chmod +x ./release/FUNCTIONAL
          ./FUNCTIONAL
          cd ../UNIT/
          qmake ../../UNIT/UNIT.pro
          make
          chmod +x ./release/UNIT
          ./UNIT
          
#          make clean
#          make api
#          make test_func
#          make test_unit
#          cd ./bin
#          chmod +x funcional_tests
#          chmod +x unit_tests
#          cd ../
#          make run_unit
#          make run_func
